// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCasino.DatabaseContext;

#nullable disable

namespace OnlineCasino.Migrations
{
    [DbContext(typeof(OnlineCasinoContext))]
    partial class OnlineCasinoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnlineCasino.DatabaseContext.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AvailableDevices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayIndex")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableDevices = "Desktop",
                            DisplayIndex = 1,
                            DisplayName = "Game A",
                            GameCategory = 0,
                            ReleaseDate = new DateTime(2024, 3, 22, 15, 1, 44, 774, DateTimeKind.Local).AddTicks(1047),
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = 2,
                            AvailableDevices = "Desktop",
                            DisplayIndex = 2,
                            DisplayName = "Game B",
                            GameCategory = 0,
                            ReleaseDate = new DateTime(2024, 3, 22, 15, 1, 44, 774, DateTimeKind.Local).AddTicks(1121),
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = 3,
                            AvailableDevices = "Desktop",
                            DisplayIndex = 1,
                            DisplayName = "Game C",
                            GameCategory = 2,
                            ReleaseDate = new DateTime(2024, 3, 22, 15, 1, 44, 774, DateTimeKind.Local).AddTicks(1180),
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = 4,
                            AvailableDevices = "Desktop",
                            DisplayIndex = 2,
                            DisplayName = "Game D",
                            GameCategory = 2,
                            ReleaseDate = new DateTime(2024, 3, 22, 15, 1, 44, 774, DateTimeKind.Local).AddTicks(1184),
                            Thumbnail = ""
                        },
                        new
                        {
                            Id = 5,
                            AvailableDevices = "Desktop",
                            DisplayIndex = 1,
                            DisplayName = "Game E",
                            GameCategory = 0,
                            ReleaseDate = new DateTime(2024, 3, 22, 15, 1, 44, 774, DateTimeKind.Local).AddTicks(1188),
                            Thumbnail = ""
                        });
                });

            modelBuilder.Entity("OnlineCasino.DatabaseContext.Entities.GameCollectionGame", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GameCollectionId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GameCollectionId");

                    b.HasIndex("GameCollectionId");

                    b.ToTable("GameCollectionsGames", (string)null);

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GameCollectionId = 1
                        },
                        new
                        {
                            GameId = 2,
                            GameCollectionId = 1
                        },
                        new
                        {
                            GameId = 3,
                            GameCollectionId = 2
                        },
                        new
                        {
                            GameId = 4,
                            GameCollectionId = 2
                        },
                        new
                        {
                            GameId = 5,
                            GameCollectionId = 3
                        });
                });

            modelBuilder.Entity("OnlineCasino.DatabaseContext.Entities.GameCollections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DisplayIndex")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCollectionId");

                    b.ToTable("GameCollections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayIndex = 1,
                            DisplayName = "Featured Games"
                        },
                        new
                        {
                            Id = 2,
                            DisplayIndex = 2,
                            DisplayName = "Top Rated"
                        },
                        new
                        {
                            Id = 3,
                            DisplayIndex = 1,
                            DisplayName = "Classic Slots",
                            ParentCollectionId = 1
                        },
                        new
                        {
                            Id = 4,
                            DisplayIndex = 2,
                            DisplayName = "Table Games"
                        },
                        new
                        {
                            Id = 5,
                            DisplayIndex = 1,
                            DisplayName = "Roulette",
                            ParentCollectionId = 4
                        });
                });

            modelBuilder.Entity("OnlineCasino.DatabaseContext.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "password1",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "password2",
                            UserName = "user2"
                        });
                });

            modelBuilder.Entity("OnlineCasino.DatabaseContext.Entities.GameCollectionGame", b =>
                {
                    b.HasOne("OnlineCasino.DatabaseContext.Entities.GameCollections", "GameCollection")
                        .WithMany()
                        .HasForeignKey("GameCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCasino.DatabaseContext.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameCollection");
                });

            modelBuilder.Entity("OnlineCasino.DatabaseContext.Entities.GameCollections", b =>
                {
                    b.HasOne("OnlineCasino.DatabaseContext.Entities.GameCollections", null)
                        .WithMany("SubCollections")
                        .HasForeignKey("ParentCollectionId");
                });

            modelBuilder.Entity("OnlineCasino.DatabaseContext.Entities.GameCollections", b =>
                {
                    b.Navigation("SubCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
